name: branch-coverage

on:
  push:
  pull_request:

jobs:
  branch-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: .go-version
          cache: true
      - name: ripgrep
        run: sudo apt-get update && sudo apt-get install -y ripgrep
      - name: branch-coverage
        env:
          EVENT_NAME: ${{ github.event_name }}
          BEFORE_SHA: ${{ github.event.before }}
          PR_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: make branch-coverage
