name: ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: .go-version
          cache: true
      - name: line-cap
        run: go tool lefthook run pre-commit --command line-cap --all-files
      - name: lint
        run: make lint
      - name: test
        if: always()
        run: make test
      - name: e2e
        if: always()
        run: make e2e
